name: apple-csp-signing-demo
on: workflow_dispatch

env:
  SIGNING_CERTIFICATE: "Apple Development: Ivan Wallis (W98N684K7V)"
  TPP_AUTH_URL: ${{ secrets.TPP_AUTH_URL }}
  TPP_HSM_URL: ${{ secrets.TPP_HSM_URL }}
  TPP_USERNAME: sample-demo-user
  TPP_PASSWORD: ${{ secrets.TPP_DEMO_PASSWORD }}

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Install client
        run: |
          curl -o "Venafi CodeSign Protect Clients v23.1.0.dmg" https://vh.venafilab.com/csc/clients/venafi-csc-latest-x86_64.dmg
          mkdir -p installer
          sudo hdiutil attach "Venafi CodeSign Protect Clients v23.1.0.dmg" -noautoopen -mountpoint installer/
          sudo installer -pkg "installer/Venafi CodeSign Protect Clients.pkg/" -target /
          sudo hdiutil detach installer
      - name: Register driver
        run: |
          echo "Asking pluginkit to unregister all plugins"
          pluginkit -v -D -m -i com.venafi.codesigning.client.application.driver | sed 's/[^/]*//' | xargs -L1 -I {} pluginkit -r {} 
          echo "Asking pluginkit to load the plugin that was just installed"
          pluginkit -v -a "/Applications/Venafi Code Signing Client.app/Contents/PlugIns/Venafi Code Signing Token Driver.appex"
          echo "Loaded plugins"
          sleep 1
          pluginkit -v -D -m -i com.venafi.codesigning.client.application.driver
          echo "Restarting the CryptoTokenKit Daemon (ctkd)"
          killall ctkd
          echo "Complete"
      - name: Sign with xcode
        run: |
          tkdriverconfig getgrant --force --authurl=${{ env.TPP_AUTH_URL }} --hsmurl=${{ env.TPP_HSM_URL }} --username=${{ env.TPP_USERNAME }} --password=${{ env.TPP_PASSWORD }}
          tkdriverconfig sync
          tkdriverconfig listobjects
          security export-smartcard token
          codesign --force -o runtime --sign "${{ env.SIGNING_CERTIFICATE }}" archives.xcarchive/Products/Applications/SampleIOSApp.app
