name: Build Push Sign
#on: { push: { branches: ['main'] } }
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v2.3.5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Login to GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: zosocanuck
          password: ${{ secrets.DOCKER_HUB }}

      - name: build+push
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: ghcr.io/zosocanuck/sample-venafi-csp-image:v0.1
          secrets:
            GIT_AUTH_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
