name: cosign-pkcs11-image-sample
#on: { push: { branches: ['main'] } }
on: workflow_dispatch

env:
  IMAGE: ghcr.io/zosocanuck/cert-manager-dashboard
  TAG: 0.1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write

    steps:
      - name: Login to Github
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Sign with cosign
        uses: addnab/docker-run-action@v3
        with:
          image: zosocanuck/test-venafi-image:latest
          run: |
            venafi-sign-cosign
        env:
          CERTIFICATE_LABEL: nirmata-dev-demo
          TPP_AUTH_URL: ${{ secrets.TPP_AUTH_URL }}
          TPP_HSM_URL: ${{ secrets.TPP_HSM_URL }}
          TPP_USERNAME: sample-cs-user
          TPP_PASSWORD: ${{ secrets.TPP_PASSWORD }}
          IMAGE: ghcr.io/zosocanuck/cert-manager-dashboard:0.1
