name: cosign-pkcs11-build
#on: { push: { branches: ['main'] } }
on: workflow_dispatch

env:
  CERTIFICATE_LABEL: nirmata-dev-demo
  TPP_AUTH_URL: ${{ secrets.TPP_AUTH_URL }}
  TPP_HSM_URL: ${{ secrets.TPP_HSM_URL }}
  TPP_USERNAME: nirmata
  TPP_PASSWORD: ${{ secrets.TPP_NIRMATA_PASSWORD }}
  IMAGE: ghcr.io/zosocanuck/sample-venafi-csp-image
  IMAGE_TEST: localhost:5000/sample-venafi-csp-image
  TAG: signed

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zosocanuck/venafi-csp-cosign:ubuntu
    permissions:
      packages: write
      id-token: write
      issues: write

    steps:
      - uses: actions/checkout@v2.3.5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: zot
        run: |    
          docker run --rm -d -p 5000:5000 --name registry registry:2
      - name: build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMAGE_TEST }}:${{ env.TAG }}
      - name: Sign with cosign
        run: |
          pkcs11config getgrant --force --authurl=$TPP_AUTH_URL --hsmurl=$TPP_HSM_URL --username=$TPP_USERNAME --password=$TPP_PASSWORD
          cosign generate ${{ env.IMAGE_TEST }}:${{ env.TAG }}
          # echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign --key "pkcs11:slot-id=0;object=${{ env.CERTIFICATE_LABEL }}?module-path=/opt/venafi/codesign/lib/venafipkcs11.so&pin-value=1234" {}@${{ steps.build-and-push.outputs.digest }}
