name: cosign-pkcs11-build
#on: { push: { branches: ['main'] } }
on: workflow_dispatch

env:
  IMAGE: ghcr.io/zosocanuck/sample-venafi-csp-image
  IMAGE_TEST: test/sample-venafi-csp-image
  TAG: signed

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zosocanuck/venafi-csp-cosign:ubuntu
    permissions:
      packages: write
      id-token: write
      issues: write

    steps:
      - uses: actions/checkout@v2.3.5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Login to GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: build
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: ${{ env.IMAGE_TEST }}:${{ env.TAG }}
          secrets:
            GIT_AUTH_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Sign with cosign
        run: |
          pkcs11config getgrant --force --authurl=$TPP_AUTH_URL --hsmurl=$TPP_HSM_URL --username=$TPP_USERNAME --password=$TPP_PASSWORD
          cosign generate ${{ env.IMAGE_TEST }}:${{ env.TAG }}
