name: Windows 2022 test

on: workflow_dispatch

jobs:
  build:
    permissions:
      packages: write
      contents: read
      id-token: write
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GHCR_TOKEN}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile.cspwindows2022 --tag ghcr.io/zosocanuck/venafi-csp-windows
    - name: Push Docker image
      run: docker push ghcr.io/zosocanuck/venafi-csp-windows
