name: Signtool demo

on: workflow_dispatch

jobs:

  build:
    # runs-on: self-hosted
    runs-on: windows-latest
    permissions: 
      id-token: write

    steps:
      - name: Install Venafi CodeSign Protect client
        shell: cmd
        run: |
          curl -o "VenafiCodeSigningClients-24.1.0-x64.msi" https://vh.venafilab.com/csc/clients/venafi-csc-latest-x86_64.msi
          start /wait msiexec /qn /i "VenafiCodeSigningClients-24.1.0-x64.msi"
          setx /M PATH "${env:PATH};${env:ProgramFiles}\Venafi CodeSign Protect"
      - name: Get OIDC Token
        uses: tremolosecurity/action-generate-oidc-jwt@v1.0
        with:
          audience: "vsign-image-signer"
          environmentVariableName: "VSIGN_JWT"
      - name: Create JWT file
        uses: DamianReeves/write-file-action@master
        with:
          path: ${{ github.workspace }}/csp.jwt
          contents: |
            ${{ env.VSIGN_JWT }}
      - name: configure CSP
        shell: cmd
        run: |
          setx /M PATH "${env:PATH};${env:ProgramFiles}\Venafi CodeSign Protect"
          cspconfig getgrant --force --authurl=https://vh.venafilab.com/vedauth --hsmurl=https://vh.venafilab.com/vedhsm --jwtfile=${{ github.workspace}}/csp.jwt
      - name: Sign application
        run: signtool sign /fd sha256 /n signer.example.com c:\temp\sample.exe
