name: csp-complete-install

on:
  workflow_dispatch:

jobs:
  install_job:
    runs-on: windows-latest
    name: CSP complete install
    steps:
      - name: Install and configure CSP client
        run: |
          curl -o "VenafiCodeSigningClients-24.3.0-x64.msi" https://vh.venafilab.com/csc/clients/venafi-csc-latest-x86_64.msi
          start /wait msiexec /qn /i "VenafiCodeSigningClients-24.3.0-x64.msi"
          "c:\program files\venafi\codesign protect\cspconfig.exe" version
