name: Signtool demo

on: workflow_dispatch

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Get GitHub OIDC token
        shell: powershell
        run: |
          $AUDIENCE="vsign-image-signer"
          $OIDC_URL_WITH_AUDIENCE="$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUDIENCE"
          echo "$GITHUB_JWT=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" -H "Accept: application/json; api-version=2.0" "$OIDC_URL_WITH_AUDIENCE" | jq -r .value)" >> $env:GITHUB_ENV
          echo $env:GITHUB_JWT > jwt.txt
          cat jwt.txt
      # - name: Sign application
      #  run: signtool sign /fd sha256 /n signer.example.com c:\temp\sample.exe
