name: Windows test

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.cspwindows --tag zosocanuck/csp-test
