name: Jarsigner demo

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
    steps:
      - name: Get Venafi CSP client
        run: |
          curl -o "venafi-codesigningclients-24.1.0-linux-x86_64.deb" https://vh.venafilab.com/csc/clients/venafi-csc-latest-x86_64.deb
          sudo dpkg -i "venafi-codesigningclients-24.1.0-linux-x86_64.deb"
      - name: Get GitHub OIDC token
        run: |
          $AUDIENCE="vsign-image-signer"
          $OIDC_URL_WITH_AUDIENCE="$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUDIENCE"
          echo "$GITHUB_JWT=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" -H "Accept: application/json; api-version=2.0" "$OIDC_URL_WITH_AUDIENCE" | jq -r .value)" >> $env:GITHUB_ENV
      - name: Create JWT file
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: ${{ github.workspace }}/csp.jwt
          contents: |
            ${{ env.GITHUB_JWT }}
      - name: Authenticate
        run: |
          /opt/venafi/codesign/bin/pkcs11config getgrant --force --authurl=https://vh.venafilab.com/vedauth --hsmurl=https://vh.venafilab.com/vedhsm --jwtfile=${{ github.workspace}}/csp.jwt
      - name: Get jar file to sign
        run: |
          wget https://vh.venafilab.com/poc_guide/test.jar -O ~/test.jar
      - name: Get Venafi CSP PKCS#11 configuration file
        run: |
          wget https://vh.venafilab.com/poc_guide/venafipkcs11.txt -O ~/venafipkcs11.txt
      - name: Sign application using jarsigner
        run: jarsigner -verbose -J-Djava.security.debug=sunpkcs11 -keystore NONE -storetype PKCS11 -storepass none -providerclass sun.security.pkcs11.SunPKCS11 -providerArg ~/venafipkcs11.txt -certs -tsa http://vh.venafilab.com/timestamp ~/test.jar vsign-rsa2048-cert
