name: Jarsigner demo

on: workflow_dispatch

#env:
#    IMAGE: ghcr.io/zosocanuck/sample-venafi-csp-image@sha256:521311a0923441ac832704e7b9fe4daa0a04685a01c9cf54ff3382fd1cde9411 #signed
#    PLUGIN_VERSION: v0.1.0-beta

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
    steps:
      - name: Get Venafi CSP client
        run: |
          curl -o "venafi-codesigningclients-24.1.0-linux-x86_64.deb" https://vh.venafilab.com/csc/clients/venafi-csc-latest-x86_64.deb
          sudo dpkg -i "venafi-codesigningclients-24.1.0-linux-x86_64.deb"
      - name: Get GitHub OIDC token
        run: |
          AUDIENCE="vsign-image-signer"
          OIDC_URL_WITH_AUDIENCE="$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUDIENCE"
          echo "VSIGN_JWT=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" -H "Accept: application/json; api-version=2.0" "$OIDC_URL_WITH_AUDIENCE" | jq -r .value)" >> $GITHUB_ENV
      - name: Create JWT file
        uses: DamianReeves/write-file-action@master
        with:
          path: ${{ github.workspace }}/csp.jwt
          contents: |
            ${{ env.VSIGN_JWT }}
#        env:
#          VSIGN_PROJECT: vsign\ztpki-rsa2048
      - name: Authenticate
        run: |
          /opt/venafi/codesign/bin/pkcs11config getgrant --force --authurl=https://vh.venafilab.com/vedauth --hsmurl=https://vh.venafilab.com/vedhsm --jwtfile=${{ github.workspace}}/csp.jwt
      - name: Get jar file to sign
        run: |
          wget https://vh.venafilab.com/poc_guide/test.jar -O ~/test.jar
      - name: Get Venafi CSP PKCS#11 configuration file
        run: |
          wget https://vh.venafilab.com/poc_guide/venafipkcs11.txt -O ~/venafipkcs11.txt
      - name: Sign application using jarsigner
        run: jarsigner -verbose -J-Djava.security.debug=sunpkcs11 -keystore NONE -storetype PKCS11 -storepass none -providerclass sun.security.pkcs11.SunPKCS11 -providerArg ~/venafipkcs11.txt -certs -tsa http://vh.venafilab.com/timestamp ~/test.jar vsign-rsa2048-cert
