name: model-signing-demo
on: workflow_dispatch

env:
  CERTIFICATE_LABEL: test-cert
  TPP_AUTH_URL: ${{ secrets.TPP_AUTH_URL }}
  TPP_HSM_URL: ${{ secrets.TPP_HSM_URL }}
  TPP_USERNAME: sample-pkcs11-tester
  TPP_PASSWORD: ${{ secrets.TPP_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zosocanuck/model-signing:latest

    steps:
      - name: Sign model with sigstore model_signing python library
        run: |
          pkcs11config getgrant --force --authurl=$TPP_AUTH_URL --hsmurl=$TPP_HSM_URL --username=$TPP_USERNAME --password=$TPP_PASSWORD
          git clone --depth=1 "https://huggingface.co/bert-base-uncased"
          rm -rf bert-base-uncased/.git
          cd bert-base-uncased
          python -m model_signing sign pkcs11-key --signature /root/model.sig --pkcs11_uri "pkcs11:token=Remote%20Token;slot-id=0;id=%74%65%73%74%2d%63%65%72%74?module-path=/opt/venafi/codesign/lib/venafipkcs11spy.so&pin-value=1234" .
          pkcs11config getpublickey --label=test-cert --filename=/root/test-cert.pub
          python -m model_signing verify key --signature /root/model.sig --public_key /root/test-cert.pub .
