name: notation-venafi-csp-plugin-summit23
on: workflow_dispatch

env:
    IMAGE: ghcr.io/zosocanuck/net-monitor:v1
    NOTATION_VERSION: 1.1.0
    PLUGIN_VERSION: 0.3.0
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write

    steps:
      - name: Login to Github
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Setup notation CLI
        uses: notaryproject/notation-action/setup@v1
        with:
          version: ${{ env.NOTATION_VERSION }}
      - name: Install Venafi plugin
        run: |
          notation plugin install --url https://github.com/Venafi/notation-venafi-csp/releases/download/v${{ env.PLUGIN_VERSION }}/notation-venafi-csp-linux-amd64.tar.gz --sha256sum ${{ env.PLUGIN_LINUX_AMD64_SHA256 }}
          notation plugin ls
      - name: Get GitHub OIDC token
        run: |
          AUDIENCE="vsign-image-signer"
          OIDC_URL_WITH_AUDIENCE="$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUDIENCE"
          echo "VSIGN_JWT=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" -H "Accept: application/json; api-version=2.0" "$OIDC_URL_WITH_AUDIENCE" | jq -r .value)" >> $GITHUB_ENV
      - name: Create config.ini
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: ${{ github.workspace }}/config.ini
          contents: |
            tpp_url=${{ secrets.TPP_URL }}
            # access_token=${{ secrets.TPP_TOKEN }}
            jwt=${{ env.VSIGN_JWT }}
            tpp_project=${{ env.VSIGN_PROJECT }}
        env:
          VSIGN_PROJECT: vsign\ztpki-rsa2048
      - name: Sign with notation
        run: |
          # export NOTATION_EXPERIMENTAL=1
          notation key add ${{ env.CERTIFICATE_LABEL }} --plugin venafi-csp --id ${{ env.CERTIFICATE_LABEL }} --plugin-config "config"="${{ github.workspace }}/config.ini"
          notation sign -k ${{ env.CERTIFICATE_LABEL }} $IMAGE
        env:
          CERTIFICATE_LABEL: vsign-ztpki-rsa2048
