name: oidc-venafi-csp-testing
on: workflow_dispatch

env:
  IMAGE: ghcr.io/zosocanuck/sample-venafi-csp-image-test
  TAG: signed

jobs:
  job:
    environment: Production
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      issues: write
    steps:
      - uses: actions/checkout@v2.3.5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Login to GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: build+push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMAGE }}:${{ env.TAG }}
          secrets:
            GIT_AUTH_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
            
      - name: Install vsign
        uses: zosocanuck/vsign-action@main 
        
      - name: OIDC Authenticate and Sign image with a key
        run: |
          AUDIENCE="vsign-image-signer"
          OIDC_URL_WITH_AUDIENCE="$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUDIENCE"
          VSIGN_JWT=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" -H "Accept: application/json; api-version=2.0" "$OIDC_URL_WITH_AUDIENCE" | jq -r .value)

          # Print decoded token information for debugging purposes
          echo $VSIGN_JWT | jq -R 'split(".") | .[1] | @base64d | fromjson'
          vsign sign --image $IMAGE:$TAG --mechanism 64
        env:
          VSIGN_URL: https://vh.venafilab.com
          VSIGN_PROJECT: nirmata\dev-demo
   
          
