name: oidc-venafi-csp-testing
on: workflow_dispatch

jobs:
  job:
    environment: Production
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Create OIDC Token
        id: create-oidc-token
        run: |
          AUDIENCE="my-kubernetes-cluster"
          OIDC_URL_WITH_AUDIENCE="$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUDIENCE"
          IDTOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" -H "Accept: application/json; api-version=2.0" "$OIDC_URL_WITH_AUDIENCE" | jq -r .value)
          echo "::add-mask::${IDTOKEN}"
          echo "::set-output name=idToken::${IDTOKEN}"

          # Print decoded token information for debugging purposes
          echo $IDTOKEN
          echo $IDTOKEN | jq -R 'split(".") | .[1] | @base64d | fromjson'
