name: qensus-csp-action-init-configuration
on:
  workflow_dispatch
  
jobs:
  example:
    runs-on: ubuntu-latest

    permissions: {}

    name: Example including initial configuration
    steps:
      - name: Setup CSPDriver
        uses: qensus-labs/venafi-codesigning-wrapper-action@v1.0.0
        with:
          tpp-csc-url: 'https://vh.venafilab.com/csc'
          tpp-auth-url: 'https://vh.venafilab.com/vedauth'
          tpp-hsm-url: 'https://vh.venafilab.com/vedhsm'
          include-config: 'true'
          tpp-user: 'signer'
      - name: Check CSPDriver (version)
        run: pkcs11config --version
