name: notation-venafi-csp-plugin
#on: { push: { branches: ['main'] } }
on: workflow_dispatch

env:
  IMAGE: ivanvenafi.azurecr.io/sample-venafi-csp-image
  TAG: signed

jobs:
  build:
    runs-on: macos-latest
    permissions:
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v2.3.5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Login to Azure
        uses: docker/login-action@v2
        with:
          registry: ivanvenafi.azurecr.io
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}

      - name: build+push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMAGE }}:${{ env.TAG }}
