name: notation-venafi-csp-plugin
#on: { push: { branches: ['main'] } }
on: workflow_dispatch

env:
  IMAGE: ghcr.io/zosocanuck/sample-venafi-csp-image
  TAG: signed
  PLUGIN_VERSION: v0.1.0-alpha.2

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write

    steps:
      - name: Login to Github
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: zosocanuck
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Install notation with plugin
        uses: zosocanuck/notation-venafi-csp-action@main
        with:
          notation-venafi-csp-release: ${{ env.PLUGIN_VERSION }}
      - name: Create config.ini
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ github.workspace }}/config.ini
          contents: |
            tpp_url=${{ env.VSIGN_URL }}
            access_token=${{ env.VSIGN_TOKEN }}
            tpp_project=${{ env.VSIGN_PROJECT }}
        env:
          VSIGN_URL: https://vh.venafilab.com
          VSIGN_TOKEN: ${{ secrets.VSIGN_TOKEN }}
          VSIGN_PROJECT: nirmata\dev-demo
      - name: Create vhroot cert file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ github.workspace }}/vhroot.crt
          contents: ${{ secrets.VH_ROOT_CERT }}
      - name: Sign with notation
        run: |
          notation key add $CERTIFICATE_LABEL --plugin venafi-csp --id $CERTIFICATE_LABEL --plugin-config "config"="${{ github.workspace }}/config.ini"
          notation certificate add --type ca --store venafilab.com ${{ github.workspace }}/vhroot.crt
          notation sign --key $CERTIFICATE_LABEL $IMAGE:$TAG
        env:
          CERTIFICATE_LABEL: nirmata-dev-demo
          NOTATION_USERNAME: zosocanuck
          NOTATION_PASSWORD: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
