name: notation-venafi-csp-plugin
#on: { push: { branches: ['main'] } }
on: workflow_dispatch

env:
  IMAGE: ivanvenafi.azurecr.io/net-monitor
  TAG: v1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write

    steps:
      - name: Login to Azure
        uses: docker/login-action@v2
        with:
          registry: ivanvenafi.azurecr.io
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}
      - name: Install notation with plugin
        uses: zosocanuck/notation-venafi-csp-action@main
      - name: Create config.ini
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ github.workspace }}/config.ini
          contents: |
            tpp_url=${{ env.VSIGN_URL }}
            access_token=${{ env.VSIGN_TOKEN }}
            tpp_project=${{ env.VSIGN_PROJECT }}
        env:
          VSIGN_URL: https://vh.venafidemo.com
          VSIGN_TOKEN: ${{ secrets.VSIGN_TOKEN }}
          VSIGN_PROJECT: nirmata\dev-demo
      - name: Sign with notation
        run: |
          cat ~/config.ini
          notation key add --name $CERTIFICATE_LABEL --plugin venafi-csp --id $CERTIFICATE_LABEL --pluginConfig "config"="/home/runner/work/sample-venafi-csp-pipeline/sample-venafi-csp-pipeline/config.ini"
          notation sign --key $CERTIFICATE_LABEL $IMAGE:$TAG
        env:
          CERTIFICATE_LABEL: nirmata-dev-demo
          NOTATION_USERNAME: ${{ secrets.AZURE_USERNAME }}
          NOTATION_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
