name: Signtool demo with NGTS

on: workflow_dispatch

env:
  NGTS_HOST_ID: 1431985321   
  NGTS_CLIENT_ID: ba0bde2c-7a13-11f1-afce-de74cc99657f

jobs:
  build:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Create temporary key file
        id: create-key
        shell: powershell
        env:
          NGTS_PRIVATE_KEY: ${{ secrets.NGTS_PRIVATE_KEY }}
        run: |
          $tempKeyPath = [System.IO.Path]::GetTempFileName()
          Set-Content -Path $tempKeyPath -Value $env:NGTS_PRIVATE_KEY -NoNewline
          Add-Content -Path $env:GITHUB_OUTPUT -Value "KEY_PATH=$tempKeyPath"

      - name: Configure CSP
        shell: powershell
        run: |
          cspconfig login --host "${{ env.NGTS_HOST_ID }}.ngts.paloaltonetworks.com" --clientid "${{ env.NGTS_CLIENT_ID }}" --keyfile "${{ steps.create-key.outputs.KEY_PATH }}" --force          
          cspconfig sync

      - name: Sign application
        run: signtool sign /fd sha256 /n builtin-test-signer c:\temp\sample.exe

      - name: Delete temporary key file
        if: always()
        shell: powershell
        run: |
          $keyPath = "${{ steps.create-key.outputs.KEY_PATH }}"
          if ($keyPath -and (Test-Path $keyPath)) {
            Remove-Item -Path $keyPath -Force
          }
