name: SLSA artifact attestation demo

on: workflow_dispatch

jobs:

  archive-build-artifacts:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
      - name: install dependencies
        run: sudo apt-get install --no-install-recommends -y libpcsclite-dev
      - name: install Venafi CSP
        run: |
          curl -o "venafi-codesigningclients-24.3.0-linux-x86_64.deb" https://vh.venafilab.com/csc/clients/venafi-csc-latest-x86_64.deb
          sudo dpkg -i "venafi-codesigningclients-24.3.0-linux-x86_64.deb"
      - name: Get OIDC Token
        uses: tremolosecurity/action-generate-oidc-jwt@v1.0
        with:
          audience: "vsign-image-signer"
          environmentVariableName: "VSIGN_JWT"
      - name: Checkout actions-oidc-debugger
        uses: actions/checkout@v3
        with:
          repository: github/actions-oidc-debugger
          path: ./.github/actions/actions-oidc-debugger
      - name: Debug OIDC Claims
        uses: ./.github/actions/actions-oidc-debugger
        with:
          audience: '${{ github.server_url }}/${{ github.repository_owner }}'
      - name: Create JWT file
        uses: DamianReeves/write-file-action@master
        with:
          path: ${{ github.workspace }}/csp.jwt
          contents: |
            ${{ env.VSIGN_JWT }}
          write-mode: overwrite
      - name: upload jwt
        uses: actions/upload-artifact@v4
        with: 
            name: my-file
            path: ${{ github.workspace }}/csp.jwt
      - name: configure CSP
        run: |
          pkcs11config getgrant --force --authurl=https://vh.venafilab.com/vedauth --hsmurl=https://vh.venafilab.com/vedhsm --jwtfile=${{ github.workspace}}/csp.jwt    
      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          cd downloads
          echo 'alpha'    > alpha.html
          echo 'bravo'    > bravo.html
          echo 'charlie'  > charlie.html
          cd ..
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v4
        with: 
          name: assets-for-download
          path: downloads
      - name: Artifact Attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '${{ github.workspace }}/downloads'
      - name: SBOM generation
        uses: anchore/sbom-action@v0
        with:
          path: '${{ github.workspace }}/downloads'
      - name: Install Cosign
        run: |
          wget https://github.com/sigstore/cosign/releases/download/v2.4.0/cosign-linux-pivkey-pkcs11key-amd64 -O cosign 
          chmod +x cosign
      - name: Sign SBOM with cosign and Venafi CSP
        run: |
          ./cosign sign --tlog-upload=false --key "pkcs11:slot-id=0;object=vsign-ztpki-rsa2048?module-path=/opt/venafi/codesign/lib/venafipkcs11.so&pin-value=1234" --new-bundle-format=true --bundle net-monitor-cosign-bundle ~/net-monitor.spdx
      - name: Upload Signed SBOM 
        uses: actions/upload-artifact@v4
        with: 
          name: signed-sbom
          path: net-monitor-cosign-bundle
